# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8087f2f0860e7fbd25466e6d9864ec11c3105d8e1dc457a0e6ccc53cb1744cebf681ce742b533f39f40579770fd7d1a0cc882f6885989246f650862927f7ab55

test:
  secret_key_base: b9ac59a69c688ff6dbe14ffd7d0b948a6f30d9bd395c4083a26803166b08b10d3cf8cc6c319ea2bf911702eb736efe0af622a7856d7542300b0afc00c36bfa0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
